[package]
name = "program_data_fetch"
version = "0.1.0"
edition = "2021"


[lints]
workspace = true

[dependencies]
solana-client = "*"
solana-pubkey = "2.4.0"
solana-sdk = "2.3.1"
tokio = { version = "1", features = ["full"] }
